[color]
; Dark murky green-black
background = #141611
; Mossy highlight
background-alt = #2B2E25

; Dusty petal gold
foreground = #C7B682
; Foggy sage gray
foreground-alt = #757B69

; Dark ochre accent
primary = #8E7E46

; Muted accents
red = #7D3A2C
yellow = #D4A747
